sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tA68LAYVkcGmyRqGVds
    access-key-secret: 1RWr3uvcGsuXxXHtpXEgigGVPPNYo6
    bucket-name: chen01-take-out
  redis:
    host: localhost
    port: 6379
    database: 0
  wechat:
    appid: wx65bc733830d10876
    secret: 06691c2814217c4b8d9275cf66917093
